FROM debian:buster-slim

LABEL maintainer="calvintam236"
LABEL description="MoneroD in Docker. Full node. Supports CPU mining."

WORKDIR /tmp/

ADD \
https://downloads.getmonero.org/cli/monero-linux-x64-v0.17.1.1.tar.bz2 \
.

RUN \
tar -jxvf monero-linux-x64-v0.17.1.1.tar.bz2 \
&& mv monero-linux-x64-v0.17.1.1/monerod /usr/local/bin/ \
&& chmod +x /usr/local/bin/monerod \
&& rm -r *

ENTRYPOINT ["monerod"]
CMD ["--help"]
